{
 "title": "SmartMeter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Meter",
   "type": "stat",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  cast(wp as float) AS \"Water pulse counter\"\r\nFROM mtopeniot.etsensoren\r\nWHERE\r\n  $__timeFilter(time_index)\r\nORDER BY time_index desc"
    },
    {
     "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  cast(gp as float)/1000 AS \"Gas pulse counter\"\r\nFROM mtopeniot.etsensoren\r\nWHERE\r\n  $__timeFilter(time_index)\r\nORDER BY time_index desc"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_index,365d),\n  sum(cast(pt as float)/3600) AS \"Power pulse counter\"\nFROM mtopeniot.etsensoren\nWHERE\n  $__timeFilter(time_index)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Water",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_index,15m),\n  avg(cast(wa as float)) AS \"Water average Rate\"\nFROM mtopeniot.etsensoren\nWHERE\n  $__timeFilter(time_index)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Gas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_index,15m),\n  avg(cast(ga as float)) AS \"Gas average Rate\"\nFROM mtopeniot.etsensoren\nWHERE\n  $__timeFilter(time_index)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Power consumed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  cast(pt as float) AS \"Total Power consumed\"\r\nFROM mtopeniot.etsensoren\r\nWHERE\r\n  $__timeFilter(time_index)\r\nORDER BY time_index desc"
    }
   ]
  },
  { "title": "Nullnummer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Water",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_index,1h),\n  avg(cast(wi as float)) AS \"Water instantaneous Rate\",\n  avg(cast(gi as float)) AS \"Gas instantaneous Rate\"\nFROM mtopeniot.etsensoren\nWHERE\n  $__timeFilter(time_index)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Meter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Water pulse counter",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "litre" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  cast(wp as float) AS \"Water pulse counter\"\r\nFROM mtopeniot.etsensoren\r\nWHERE\r\n  $__timeFilter(time_index)\r\nORDER BY time_index desc"
      }
     ]
    },
    {
     "title": "Water pulse counter",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\r\n  time_index AS \"time\",\r\n  cast(gp as float)/1000 AS \"Gas pulse counter\"\r\nFROM mtopeniot.etsensoren\r\nWHERE\r\n  $__timeFilter(time_index)\r\nORDER BY time_index desc"
      }
     ]
    },
    {
     "title": "Total Power consumed",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 14, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(time_index,365d),\n  sum(cast(pt as float)/3600) AS \"pt\"\nFROM mtopeniot.etsensoren\nWHERE\n  $__timeFilter(time_index)\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "SmartMeter TableView",
     "type": "table",
     "gridPos": { "h": 11, "w": 13, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  pt AS \"Total Power consumed\",\n  wp AS \"Water pulse counter\",\n  wa AS \"Water avg. Rate\",\n  wi AS \"Water instantaneous Rate\",\n  gp AS \"Gas pulse counter\",\n  ga AS \"Gas avg. Rate\",\n  gi AS \"Gas instantaneous Rate\"\nFROM mtopeniot.etsensoren\nWHERE\n  $__timeFilter(time_index)\nORDER BY time_index desc"
      }
     ]
    },
    {
     "title": "SmartMeter TableView",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  cast(pt as float) as \"Total Power consumed\"\nFROM mtopeniot.etsensoren\nWHERE\n  $__timeFilter(time_index)\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "SmartMeter TableView",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 13, "x": 0, "y": 38 },
     "targets": [
      {
       "rawSql": "SELECT\n  time_index AS \"time\",\n  cast(pt as float) AS \"Total Power consumed\",\n  cast(wa as float) AS \"Water avg. Rate\",\n  cast(wi as float) AS \"Water instantaneous Rate\",\n  cast(ga as float) AS \"Gas avg. Rate\",\n  cast(gi as float) AS \"Gas instantaneous Rate\"\nFROM mtopeniot.etsensoren\nWHERE\n  $__timeFilter(time_index)\nORDER BY time_index desc"
      }
     ]
    }
   ]
  }
 ]
}